# Generated by Django 4.1 on 2022-08-17 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_bio_user_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Bio',
            new_name='bio',
        ),
    ]
